name: industrial
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0-rc
  material_design_icons_flutter: 3.2.4096
  http: ^0.12.0+2
  dio: ^3.0.2
  shared_preferences: ^0.5.3+5
  toast: ^0.1.5
  carousel_slider: ^1.3.0
  page_transition: ^1.1.4
    #pinch_zoom_image: ^0.2.5
  photo_view: ^0.9.0
  badges: ^1.1.0
  random_string: ^1.1.0
  share: ^0.6.3+5
  flutter_open_whatsapp: ^0.1.2
  firebase_messaging: ^5.1.6
  google_maps_flutter: ^0.5.21+15
  location: ^2.3.5
  event_taxi: ^0.1.5
  get_version: ^0.2.0+1
  launch_review: ^2.0.0
  rounded_floating_app_bar: ^0.1.0
  webview_flutter: ^1.0.5
  fluttertoast: ^7.1.1
  flutter_swiper: ^1.1.6
  url_launcher: ^5.7.10
  permission_handler: ^3.1.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/about.jpg
    - assets/images/automation.jpg
    - assets/images/electrical.jpg
    - assets/images/mechenical.jpg
    - assets/logo-sparemaster.png
    - assets/images/twitter.png
    - assets/images/global.png
    - assets/images/linkedin.png
    - assets/images/wordpress.png
    - assets/images/facebook.png
    - assets/images/Capture.PNG
    - assets/images/banner_600x400.jpg
    - assets/images/cement_600x400.jpg
    - assets/images/steel_600x400.jpg
    - assets/images/picture.png
    - assets/images/delivery-truck.png
    - assets/images/tool-box.png
    - assets/images/products/600-mw-generator-bearing-359x283.jpg
    - assets/images/products/coal-saver-boiler-spares-359x283.jpg
    - assets/images/products/generator-bearing-359x283.jpg
    - assets/images/products/generator-carbon-brush-359x283.jpg
    - assets/images/products/generator-collector-ring-359x283.jpg
    - assets/images/products/generator-gas-station-359x283.jpg
    - assets/images/products/generator-seal-ring-359x283.jpg
    - assets/images/products/generator-sealing-oil-filter-359x283.jpg
    - assets/images/products/herbine-generator-rubber-seal-359x283.jpg
    - assets/images/products/m-03-intelligent-359x283.jpg
    - assets/images/products/m-85-intelligent-359x283.jpg
    - assets/images/products/m-intelligent-359x283.jpg
    - assets/images/products/rha-m-359x283.jpg
    - assets/images/products/vbj-high-performance-valve-359x283.jpg
    - assets/images/products/vfr-eccentric-rotary-valve-359x283.jpg
    - assets/images/products/zhjr-full-bore-ball-valve-359x283.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
